### ISSUE TITLE
Commands partially broken with Sopel 7.1.2

### ISSUE THREAD

**Issue by DrMcCoy** [xoreos/hk51-bot#1]
```
$ sopel --version
Sopel 7.1.2 (running on Python 3.9.9)
```

Works: insult, kick, die
Doesn't work: quote, root beer, duck

```
22:57:14 <@clone2727> So ones that use the stock sopel shit work and my wrappers don't
```

**Comment by clone2727** [comment]
It's probably related to sopel making [this change](https://github.com/sopel-irc/sopel/commit/ad8397c1c96add70bb744d695f8c8d487361061f). I imagine I'll have to call `rule` directly now since `_sopel_callable` is by name, internal.

**Comment by clone2727** [comment]
@DrMcCoy I pushed a new version. Could you please confirm it works for you?

**Comment by DrMcCoy** [comment]
Works, yes. Thanks! :D
